/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.7.0
 *
 * Project: 'MVE_Test+AN552_ACI' 
 * Target:  'AN552_ACI' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* GorgonMeducer::Utilities:perf_counter:Core&Source@2.4.0 */
#define __PERF_COUNTER_CFG_USE_SYSTICK_WRAPPER__ 1
/* GorgonMeducer::Utilities:perf_counter:Porting&PMU@1.1.1 */
#define __PERFC_USE_PORTING__                           1
#define __PERFC_USE_PMU_PORTING__                       1
#define __PERFC_CFG_DISABLE_DEFAULT_SYSTICK_PORTING__   1
#define __PERFC_CFG_PORTING_INCLUDE__                   "perfc_port_pmu.h"


#endif /* PRE_INCLUDE_GLOBAL_H */
